### ISSUE TITLE
More like a feature! (Question about PSG/FM YSM2413)

### ISSUE THREAD

**Issue by Zerodarkage** [ocornut/meka#126]
Hi! There is any way to mix FM and PSG musics and sounds!? 
For example: Kenseiden with "PSG special effects" but the music is "FM YSM2413"
There is any way this could be a thing or it's not possible?

Thanks in advance!

**Comment by ocornut** [comment]
I think it would requires mods in the game engine, and is likely to be something to be done on a per-game basis.
I believe this is best asked on smspower.

**Comment by Zerodarkage** [comment]
Thanks! I will do that! Because i love PSG and a MOD (per game) to use FM only on music/sound would be amazing!
I will close the "issue" for now! :D

**Comment by Zerodarkage** [comment]
Thanks! I will do that! Because i love PSG and a MOD (per game) to use FM only on music/sound would be amazing!
I will close the "issue" for now! :D
