### ISSUE TITLE
Documentation: Which machine is emulated?

### ISSUE THREAD

**Issue by spth** [ocornut/meka#17]
I cannot find any documentation on how to make Meka emulate a certain machine. From trying, it seems, .rom files are considered ColecoVision binaries and .sms files are considered Sega Master System files, but I'm not sure if that is true, or maybe Meka detected the ColecoVision header in my .rom file instead. On smspower.org someone suggested .sc when I asked for SG-1000 and SC-3000 emulation. But I have no idea if that is true (and from the lack of memory address aliasing, it probably is not).
Meka documentation should clearly state how to make Meka emulate a particular machine.

Philipp

**Comment by ocornut** [comment]
The emulated machines are listed in the documentations.
The detection is done by file extensions. The file extensions are standards.
