### ISSUE TITLE
Fix linking with allegro5 > 5.0

### ISSUE THREAD

**Issue by musuruan** [ocornut/meka#24]
If you have installed a version of allegro5 > 5.0 (for example, in Fedora 24 there is allegro5-5.2.0), the linking will fail.

You can fix this with the following command:
sed -i 's/pkg-config --cflags --libs allegro-5.0 allegro_image-5.0 allegro_audio-5.0 allegro_font-5.0 allegro_primitives-5.0 allegro_ttf-5.0/pkg-config --cflags --libs allegro-5 allegro_image-5 allegro_audio-5 allegro_font-5 allegro_primitives-5 allegro_ttf-5/' srcs/Makefile

**Comment by markvantilburg** [comment]
Might be easier to send a pull for the makefile itself.

**Comment by ocornut** [comment]
Helllo,
Should we just modify the build script to link with latest Allegro version?

**Comment by danielt3** [comment]
I think a fix in the Makefile itself (which is not automatically generated) is a good solution. Maybe creating a variable for setting the Allegro version and change the pkg-config command accordingly.

**Comment by danielt3** [comment]
I think there is no reason to target 5.0 if we can target 5.2. It is also good to document this change.

**Comment by ocornut** [comment]
I don't use Linux/Mac but I'd take PR.

**Comment by EndeavourAccuracy** [comment]
[This](http://www.smspower.org/forums/13019-Meka080WithNewSoundEngineTESTERSWANTED?start=350#103356) fixes it.
In other words, in the Makefile 6x change "5.0" to just "5" in the LIB_ALLEG line for system "unix".

**Comment by bodhi-baum** [comment]
I just a few minutes ago compiled meka with changing "5.0" to just "5" in the LIB_ALLEG line for system "unix". Now it works smoothly under Linux here. I think it would be a good idea to change the MAKEFILE.

**Comment by bodhi-baum** [comment]
I saw that it was changed already. So this issue can be closed.
