### ISSUE TITLE
Default resolution if meka.cfg included in the release

### ISSUE THREAD

**Issue by markvantilburg** [ocornut/meka#5]
In this build: meka-2015-05-06-win32-proto.zip (1002.45 KB) the .cfg file is included.

If the cfg is meant to be bundled then i would suggest to use a lower resolution for the included .cfg file as 1280x960 is not a real common resolution, maybe default to 1024x768 instead.

**Comment by ocornut** [comment]
You are right. meka.cfg shouldn't be bundled, I need to fix the dist-bin-win32.bat to exclude it.

**Comment by ocornut** [comment]
OK I have removed that. The reason I was bundling mekaw.cfg is to cater for case where the default configuration would totally fail to run on some machines. I haven't heard of such issues.
