### ISSUE TITLE
file cant be found.

### ISSUE THREAD

**Issue by Russia2013** [ocornut/meka#6]
I was trying out the Mekaw .80 and when I clicked on the .exe file it would tell me that it could not find the meka.msg file.
 I had also tried earlier version of Mekaw such as .73 and that one said it could not find the audiow32.dll.  Ironically the files seem to be there. I do not know if I am not installing it properly. I had used earlier version a few years ago and it worked quite well.

**Comment by ocornut** [comment]
That's odd it wouldn't find the file. Which operating system/setup are you using?
What's the full path to your Meka folder? There might be some issues handling Unicode characters.

**Comment by ocornut** [comment]
@Russia2013 Ping?
