### ISSUE TITLE
Windows Defender malware scan of Meka 2019-12-13 release

### ISSUE THREAD

**Issue by dagit** [ocornut/meka#60]
Just a heads up that the current release (Meka 2019-12-13) of Meka is getting flagged by windows defender as malware. Maybe you can submit the executable to them for analysis? I assume/hope it's just a false positive.

**Comment by markvantilburg** [comment]
Also some other av's are flagging it, https://www.virustotal.com/gui/file/92a4ea5c20cdef8373651f851399bc4d0459dcea285159d3ab4f700d2ac124cb/detection

**Comment by maxim-zhao** [comment]
Un-UPXing it removes almost all those false positives: https://www.virustotal.com/gui/file-analysis/N2ZmYzUwYzk4MzMzZmIyZDY1OGMwMzgwZGFiYmYxZDg6MTU5MTkwODY1Ng==/detection but sadly Microsoft remains.

**Comment by maxim-zhao** [comment]
The latest continuous build (https://ci.appveyor.com/project/ocornut/meka/build/artifacts) also triggers these problems. https://www.virustotal.com/gui/file-analysis/YjZkZGQ1MjRkZWZjZDk5ZDFiZDk2YjJmZGY2NGM0ZjM6MTU5MTkwOTM5Ng==/detection

**Comment by KrunoSaho** [comment]
Yeah, I got this as well today.
