### ISSUE TITLE
Trojan virus warning on meka-20191213 release binary

### ISSUE THREAD

**Issue by bbbradsmith** [ocornut/meka#63]
A problem with the binary in this release: https://github.com/ocornut/meka/releases/tag/meka-20191213

mekaw.exe is identified as a trojan virus by Windows Defender or Windows Security Essentials

Windows Defender identifies it as: Trojan:Win32/Fuery.B!cl

Windows Security Essentials identifies it as: Trojan:Win32/Wacatac.C!ml

If this is a false positive result, is there some problem with the way the executable is packed?

**Comment by markvantilburg** [comment]
See: #60 
probably due to use of UPX

**Comment by ocornut** [comment]
Going to try replacing the file with a non UPX compressed one....

**Comment by bbbradsmith** [comment]
Ah, after reading about UPX that does explain it. I ended up building the executable from source. I noticed that even though that EXE is about twice the size uncompressed, when zipped it's only about 100k larger than the UPXed one in the package? So, I know false positives like this aren't really your fault, but that data savings might not be worth the trade.
