### ISSUE TITLE
Sega Genesis / Mega Drive (MD), Sega CD, Sega 32X support?

### ISSUE THREAD

**Issue by MineCreeper9898** [ocornut/meka#78]
![Sega-Mega-Drive-JP-Mk1-Console-Set](https://user-images.githubusercontent.com/111442545/185157569-e5e2be6a-d9be-4f46-a2dd-c62e22ff079d.jpg)
Sega Genesis / Mega Drive is the 16-bit console in Z80 series
![gen_sega_cd_sys_01gr](https://user-images.githubusercontent.com/111442545/185157592-54d8cf0d-4dc0-42cd-b6a6-fb4ab017a175.jpg)
Sega CD is Add-on for Sega Genesis / Mega Drive
![495315CA-FFD4-4CC6-8FA9-9B3F3CF4ECF2](https://user-images.githubusercontent.com/111442545/185157606-cf18d433-1c7a-44ab-8656-b185ae708dd0.jpg)
Sega 32X is the 32-bit add-on for Sega Genesis / Mega Drive.

MEKA will be also 16-bit emulator

**Comment by ocornut** [comment]
No thank you.

**Comment by cglmrfreeman** [comment]
Thank you for the wonderful visuals. Would have never known what you were talking about without them. :roll_eyes:
